basePath: /api/v1
consumes:
    - application/json
definitions:
    DataResponse:
        properties:
            record:
                x-go-name: Record
            records:
                x-go-name: Records
        type: object
        x-go-name: data
        x-go-package: go-echo/model/base
    InsertDriverResponse:
        properties:
            created_at:
                description: |-
                    Created At
                    in: string
                example: "2023-03-30 10:39:44"
                type: string
                x-go-name: CreatedAt
            created_by:
                description: |-
                    Created By
                    in: string
                example: system
                type: string
                x-go-name: CreatedBy
            id:
                description: |-
                    ID
                    in: string
                example: 5c091047-f19c-4235-be8d-b6596aecf880
                type: string
                x-go-name: Id
            is_available:
                description: |-
                    Is Available
                    in: bool
                example: true
                type: boolean
                x-go-name: IsAvailable
            license_number:
                description: |-
                    Licensse Number
                    in: string
                example: "89011231091"
                type: string
                x-go-name: LicenseNumber
            name:
                description: |-
                    Name
                    in: string
                example: John
                type: string
                x-go-name: Name
            updated_at:
                description: |-
                    Updated At
                    in: string
                example: "2023-03-30 10:39:44"
                type: string
                x-go-name: UpdatedAt
            updated_by:
                description: |-
                    Updated By
                    in: string
                example: system
                type: string
                x-go-name: UpdatedBy
        type: object
        x-go-package: go-echo/model/response
    LoginRequestBody:
        properties:
            password:
                description: |-
                    Password of user
                    in: string
                example: "123456"
                type: string
                x-go-name: Password
            username:
                description: |-
                    Username of user
                    in: string
                example: admin
                type: string
                x-go-name: Username
        required:
            - username
            - password
        type: object
        x-go-package: go-echo/model/request
    LoginResponse:
        properties:
            token:
                description: |-
                    Token
                    in: string
                example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE3MDY1ODMwNTYsInVzZXIiOiJhZG1pbiJ9.F-bBdILVQIg9kj8mWGn5ma7qDoyzSbiUojQz6EW_hJs
                type: string
                x-go-name: Token
        type: object
        x-go-package: go-echo/model/response
    MetaResponse:
        properties:
            code:
                description: |-
                    Code is the response code
                    in: int
                format: int64
                type: integer
                x-go-name: Code
            message:
                description: |-
                    Message is the response message
                    in: string
                type: string
                x-go-name: Message
            pagination:
                $ref: '#/definitions/PaginationResponse'
        type: object
        x-go-name: metaResponse
        x-go-package: go-echo/model/base
    MetaSingleSuccessResponse:
        properties:
            code:
                description: |-
                    Code of Response
                    in: int
                example: 1000
                format: int64
                type: integer
                x-go-name: Code
            message:
                description: |-
                    Message of Response
                    in: string
                example: Success
                type: string
                x-go-name: Message
        type: object
        x-go-package: go-echo/model/entity
    PaginationResponse:
        properties:
            limit:
                format: int64
                type: integer
                x-go-name: Limit
            page:
                format: int64
                type: integer
                x-go-name: Page
            records:
                format: int64
                type: integer
                x-go-name: Records
            total_page:
                format: int64
                type: integer
                x-go-name: TotalPage
            total_records:
                format: int64
                type: integer
                x-go-name: TotalRecords
        type: object
        x-go-name: Pagination
        x-go-package: go-echo/model/base
    RegisterUserRequestBody:
        properties:
            nickname:
                description: |-
                    Nickname of user will show as profile name
                    in: string
                example: Administrator
                type: string
                x-go-name: Nickname
            password:
                description: |-
                    Password of user
                    in: string
                example: "123456"
                type: string
                x-go-name: Password
            username:
                description: |-
                    Username of user
                    in: string
                example: admin
                type: string
                x-go-name: Username
        required:
            - username
            - password
            - nickname
        type: object
        x-go-package: go-echo/model/request
    RegisterUserResponse:
        properties:
            id:
                description: |-
                    Id of user
                    in: string
                example: 4fc427da-91c7-45b5-b4f9-f6dcc646005f
                type: string
                x-go-name: Id
        type: object
        x-go-package: go-echo/model/response
    SuccessResponse:
        properties:
            data:
                $ref: '#/definitions/DataResponse'
            errors:
                additionalProperties:
                    type: string
                description: |-
                    Errors is the response message
                    in: string
                type: object
                x-go-name: Errors
            meta:
                $ref: '#/definitions/MetaResponse'
        type: object
        x-go-name: responseHttp
        x-go-package: go-echo/model/base
    UserProfileResponse:
        properties:
            Nickname:
                description: |-
                    Nickname of user
                    in: string
                example: John Doe
                type: string
            id:
                description: |-
                    Id of user
                    in: string
                example: 4fc427da-91c7-45b5-b4f9-f6dcc646005f
                type: string
                x-go-name: Id
        type: object
        x-go-package: go-echo/model/response
info:
    title: 'Echo Boilerplate API:'
    version: "1.0"
paths:
    /driver/:
        post:
            description: Add Driver
            operationId: InsertDriverRequest
            parameters:
                - description: |-
                    Name
                    in: string
                  in: query
                  name: name
                  type: string
                  x-go-name: Name
                - description: |-
                    License Number
                    in: string
                  in: query
                  name: license_number
                  type: string
                  x-go-name: LicenseNumber
                - description: |-
                    Is Available
                    in: bool
                  in: query
                  name: is_available
                  type: boolean
                  x-go-name: IsAvailable
            responses:
                "200":
                    description: Success Response.
                    schema:
                        properties:
                            data:
                                properties:
                                    record:
                                        $ref: '#/definitions/InsertDriverResponse'
                                type: object
                            meta:
                                $ref: '#/definitions/MetaSingleSuccessResponse'
            security:
                - Bearer: []
            tags:
                - Driver
    /user/login:
        post:
            description: Login user
            operationId: LoginRequest
            parameters:
                - in: body
                  name: body
                  schema:
                    $ref: '#/definitions/LoginRequestBody'
                  x-go-name: Body
            responses:
                "200":
                    description: Success Response.
                    schema:
                        properties:
                            data:
                                properties:
                                    record:
                                        $ref: '#/definitions/LoginResponse'
                                type: object
                            meta:
                                $ref: '#/definitions/MetaSingleSuccessResponse'
            tags:
                - User
    /user/profile:
        get:
            description: User profile
            operationId: UserProfileRequest
            parameters:
                - description: |-
                    Id of user
                    in: string
                  example: 4fc427da-91c7-45b5-b4f9-f6dcc646005f
                  in: query
                  name: id
                  type: string
                  x-go-name: Id
            responses:
                "200":
                    description: Success Response.
                    schema:
                        properties:
                            data:
                                properties:
                                    record:
                                        $ref: '#/definitions/UserProfileResponse'
                                type: object
                            meta:
                                $ref: '#/definitions/MetaSingleSuccessResponse'
            security:
                - Bearer: []
            tags:
                - User
    /user/register:
        post:
            description: Register user
            operationId: RegisterUserRequest
            parameters:
                - in: body
                  name: body
                  schema:
                    $ref: '#/definitions/RegisterUserRequestBody'
                  x-go-name: Body
            responses:
                "200":
                    description: Success Response.
                    schema:
                        properties:
                            data:
                                properties:
                                    record:
                                        $ref: '#/definitions/RegisterUserResponse'
                                type: object
                            meta:
                                $ref: '#/definitions/MetaSingleSuccessResponse'
            security:
                - Bearer: []
            tags:
                - User
produces:
    - application/json
    - text/html; charset=utf-8
responses:
    MetaSingleResponse:
        description: ""
        schema:
            $ref: '#/definitions/MetaSingleSuccessResponse'
schemes:
    - http
    - https
securityDefinitions:
    Bearer:
        in: header
        name: Authorization
        type: apiKey
swagger: "2.0"
