# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install Dependecies
      run: go mod tidy

    - name: Generate Mocks
      run: |
        GO_FILES=$(find ./ -name "interface.go")
        GEN_GO_FILES=$(echo "$GO_FILES" | sed 's/\.go/.mock.gen.go/g')
        for file in $GO_FILES; do
          echo "Generating mocks ${file%.go}.mock.gen.go for $file"
          mockgen -source=$file -destination=${file%.go}.mock.gen.go -package=$(basename $(dirname $file))
        done

    - name: Test
      run: go test -short -coverprofile=coverage.out -v ./... -coverpkg=./...

    - name: Build
      run: go build -v ./...
